#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run build
git add -A
git reset -- snippets/vite-tag.liquid
git update-index --skip-worktree snippets/vite-tag.liquid
cd assets
find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && pwd && git ls-files -z ${pwd} | xargs -0 git update-index --skip-worktree" \;
npx lint-staged
